use_frameworks!

platform :ios, '8.0'

target 'CYRModuleTools_Example' do
  pod 'CYRModuleTools', :path => '../'

  target 'CYRModuleTools_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
